AWSTemplateFormatVersion: '2010-09-09'
Description: "This template will deploy this job."

Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(5 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: !Ref MessageSNSTopic
          Id: "TargetSns"

  MessageSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "hongxingTopic"


  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MessageSNSTopic
      PolicyDocument:
        Id: MyTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: allow-cloudwatch-rule-public
            Effect: Allow
            Principal: '*'
            Action:
              - sns:Subscribe
              - sns:Publish
            Resource: !Ref MessageSNSTopic


  SNSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref MessageSNSTopic
      Endpoint: !GetAtt MessageQueue.Arn
      Protocol: sqs

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: 921261636@qq.com
      Protocol: email
      TopicArn: !Ref 'MessageSNSTopic'

  MessageQueue:
    Type: AWS::SQS::Queue
    DependsOn: DeadLetterQueue
    Properties:
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5

  DeadLetterQueue:
    Type: AWS::SQS::Queue