AWSTemplateFormatVersion: '2010-09-09'
Description: "This template will deploy this job."

Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn: !Ref MessageSNSTopic
          Id: "TargetSns"

  MessageSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "hongxingTopic"


  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref MessageSNSTopic
      PolicyDocument:
        Id: MyTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: allow-cloudwatch-rule-public
            Effect: Allow
            Principal: '*'
            Action:
              - sns:Subscribe
              - sns:Publish
            Resource: !Ref MessageSNSTopic


  SNSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref MessageSNSTopic
      Endpoint: !GetAtt MessageQueue.Arn
      Protocol: sqs

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: 921261636@qq.com
      Protocol: email
      TopicArn: !Ref 'MessageSNSTopic'

  MessageQueue:
    Type: AWS::SQS::Queue
    DependsOn: DeadLetterQueue
    Properties:
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5

  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MessageQueue
      PolicyDocument:
        Statement:
          - Sid: allow-send-message
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
            Resource: '*'

  DeadLetterQueue:
    Type: AWS::SQS::Queue

  LambdaFunctionHello:
    Type: AWS::Lambda::Function
    Properties:
      Handler: com.xing.SqsRequestHandler
      Role: arn:aws:iam::494526681395:role/for-aws-training-2
      Code:
        S3Bucket: hongxing-deployment-bucket
        S3Key: func/v1/sns-sqs-training-1.0-SNAPSHOT.jar
      Runtime: java8
      Timeout: 60
      MemorySize: 512

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LambdaFunctionHello
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt MessageQueue.Arn

  LambdaSQSMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt MessageQueue.Arn
      FunctionName: !GetAtt LambdaFunctionHello.Arn
